Repository slackapi/hubot-slack, pull requests merged in 2020-10, with the labels that each got.

#608 #607 Update docs for new users
  .gitignore
  docs/index.md
Labels: docs

#609 Add support for thread_broadcast message
  src/bot.coffee
  test/bot.coffee
Labels: bug, semver:patch

#610 version 4.8.1
  docs/_posts/2020-10-19-v4.8.1.md
  package.json
Labels: semver:patch
