Repository slackapi/hubot-slack, pull requests merged in 2020-04, with the labels that each got.

#587 Add Node 12 to TravisCI settings
  .travis.yml
Labels: tests

#588 Fix #586 hubot-slack calling bots.info a suspicious number of times
  src/client.coffee
Labels: bug

#565 Add compatibility for Coffeescript 2 (and hubot 3)
  .travis.yml
  src/bot.coffee
  src/message.coffee
Labels: enhancement, semver:minor
