Repository slackapi/hubot-slack, pull requests merged in 2021-01, with the labels that each got.

#619 Migrate CI builds to GitHub Actions
  .github/workflows/ci-build.yml
  .travis.yml
  codecov.yml
Labels: bug, tests

#612 make PAGE_SIZE configurable for Slack API list calls
  slack.coffee
  src/bot.coffee
  src/client.coffee
Labels: enhancement, semver:minor

#617 fix incorrect bot_id usage
  src/client.coffee
  test/client.coffee
Labels: bug

#620 version 4.9.0 release
  .github/maintainers_guide.md
  docs/_posts/2021-01-26-v4.9.0.md
  package.json
Labels: semver:minor
